{% set data = load_setup_py_data() %}

package:
  name: "addie"
  version: "{{ data['version'] }}"

source:

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:
   - CONDA_BLD_PATH

requirements:
  run:
    - h5py
    - matplotlib <3.0
    - mantid-workbench
    - mantid-total-scattering-python-wrapper
    - networkx ==2.2
    - numpy
    - python
    - pyyaml
    - scikit-image <0.15
    - scipy <1.3
    - six

about:
  home: https://github.com/neutrons/addie
  license: GPL (version 3)
  license_family: GPL3
  license_file: 
  summary: ADvanced DIffraction Environment: Mantid Total Scattering Reduction

extra:
  recipe-maintainers:
    - JeanBilheux
    - marshallmcdonnell
    - peterfpeterson
